name: CMake build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.cfg.name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { name: "Windows MSVC (VS2022)", gen: "Visual Studio 17 2022", build_type: "Debug", cc: "cl",  cxx: "cl",  use_mingw: "false" }
          - { name: "Windows MinGW (Makefiles)", gen: "MinGW Makefiles",    build_type: "Debug", cc: "gcc", cxx: "g++", use_mingw: "true"  }

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Ensure googletest is here (fail early if not)
      - name: Verify googletest submodule
        shell: pwsh
        run: |
          if (-not (Test-Path "$env:GITHUB_WORKSPACE\googletest\CMakeLists.txt")) {
            git submodule sync --recursive
            git submodule update --init --recursive
          }
          if (-not (Test-Path "$env:GITHUB_WORKSPACE\googletest\CMakeLists.txt")) {
            Write-Error "googletest submodule is missing (required when SQLITECPP_BUILD_TESTS=ON)."
          }

      # MSVC env (for the Visual Studio generator)
      - name: Setup MSVC env
        if: matrix.cfg.use_mingw == 'false'
        uses: ilammy/msvc-dev-cmd@v1

      # Install MinGW (for the MinGW Makefiles generator)
      - name: Install MinGW
        if: matrix.cfg.use_mingw == 'true'
        shell: pwsh
        run: choco install -y mingw

      - name: Add MinGW to PATH
        if: matrix.cfg.use_mingw == 'true'
        shell: bash
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> "$GITHUB_PATH"

      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cmake -S . -B build -G "${{ matrix.cfg.gen }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.build_type }} \
            -DBUILD_SHARED_LIBS=ON \
            -DSQLITECPP_BUILD_TESTS=ON \
            -DSQLITECPP_BUILD_EXAMPLES=ON \
            -DSQLITECPP_RUN_CPPCHECK=OFF \
            -DSQLITECPP_RUN_CPPLINT=OFF

      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.cfg.build_type }} -j2

      - name: Test
        shell: bash
        run: ctest --verbose --output-on-failure --test-dir build -C ${{ matrix.cfg.build_type }}
